# Generated by Django 4.2.16 on 2024-09-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='members',
        ),
    ]
